// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";


export const api = {
  routers: {
    articles: {
      extract: createApiLeaf<"action", typeof import("../routers/articles").extract>(createGeneratedFunctionReference<"action", "public", typeof import("../routers/articles").extract>("routers/articles:extract"), { type: "action" }),
    },
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

