// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";


export const api = {
  routers: {
    articles: {
      extract: createApiLeaf<"action", typeof import("../functions/routers/articles").extract>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/routers/articles").extract>("routers/articles:extract"), { type: "action" }),
    },
    tts: {
      synthesize: createApiLeaf<"action", typeof import("../functions/routers/tts").synthesize>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/routers/tts").synthesize>("routers/tts:synthesize"), { type: "action" }),
      temporaryKey: createApiLeaf<"action", typeof import("../functions/routers/tts").temporaryKey>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/routers/tts").temporaryKey>("routers/tts:temporaryKey"), { type: "action" }),
    },
    users: {
      addToPlaylist: createApiLeaf<"mutation", typeof import("../functions/routers/users").addToPlaylist>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/users").addToPlaylist>("routers/users:addToPlaylist"), { type: "mutation" }),
      deleteUserArticle: createApiLeaf<"mutation", typeof import("../functions/routers/users").deleteUserArticle>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/users").deleteUserArticle>("routers/users:deleteUserArticle"), { type: "mutation" }),
      getCurrentUser: createApiLeaf<"query", typeof import("../functions/routers/users").getCurrentUser>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/routers/users").getCurrentUser>("routers/users:getCurrentUser"), { type: "query" }),
      getUserPlaylist: createApiLeaf<"query", typeof import("../functions/routers/users").getUserPlaylist>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/routers/users").getUserPlaylist>("routers/users:getUserPlaylist"), { type: "query" }),
      saveUserProgress: createApiLeaf<"mutation", typeof import("../functions/routers/users").saveUserProgress>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/users").saveUserProgress>("routers/users:saveUserProgress"), { type: "mutation" }),
    },
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

