// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";


export const api = {
  routers: {
    articles: {
      extract: createApiLeaf<"action", typeof import("../functions/routers/articles").extract>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/routers/articles").extract>("routers/articles:extract"), { type: "action" }),
    },
    listening: {
      claim: createApiLeaf<"mutation", typeof import("../functions/routers/listening").claim>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/listening").claim>("routers/listening:claim"), { type: "mutation" }),
      create: createApiLeaf<"mutation", typeof import("../functions/routers/listening").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/listening").create>("routers/listening:create"), { type: "mutation" }),
      get: createApiLeaf<"query", typeof import("../functions/routers/listening").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/routers/listening").get>("routers/listening:get"), { type: "query" }),
      setVisibility: createApiLeaf<"mutation", typeof import("../functions/routers/listening").setVisibility>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/listening").setVisibility>("routers/listening:setVisibility"), { type: "mutation" }),
    },
    narration: {
      page: createApiLeaf<"query", typeof import("../functions/routers/narration").page>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/routers/narration").page>("routers/narration:page"), { type: "query" }),
      prepare: createApiLeaf<"action", typeof import("../functions/routers/narration").prepare>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/routers/narration").prepare>("routers/narration:prepare"), { type: "action" }),
    },
    tts: {
      generateTrackUploadUrl: createApiLeaf<"mutation", typeof import("../functions/routers/tts").generateTrackUploadUrl>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/tts").generateTrackUploadUrl>("routers/tts:generateTrackUploadUrl"), { type: "mutation" }),
      getExactTrack: createApiLeaf<"query", typeof import("../functions/routers/tts").getExactTrack>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/routers/tts").getExactTrack>("routers/tts:getExactTrack"), { type: "query" }),
      persistTrack: createApiLeaf<"mutation", typeof import("../functions/routers/tts").persistTrack>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/tts").persistTrack>("routers/tts:persistTrack"), { type: "mutation" }),
      pregenerate: createApiLeaf<"action", typeof import("../functions/routers/tts").pregenerate>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/routers/tts").pregenerate>("routers/tts:pregenerate"), { type: "action" }),
      pregenerationStatus: createApiLeaf<"query", typeof import("../functions/routers/tts").pregenerationStatus>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/routers/tts").pregenerationStatus>("routers/tts:pregenerationStatus"), { type: "query" }),
      synthesize: createApiLeaf<"action", typeof import("../functions/routers/tts").synthesize>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/routers/tts").synthesize>("routers/tts:synthesize"), { type: "action" }),
      temporaryKey: createApiLeaf<"action", typeof import("../functions/routers/tts").temporaryKey>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/routers/tts").temporaryKey>("routers/tts:temporaryKey"), { type: "action" }),
    },
    users: {
      addToPlaylist: createApiLeaf<"mutation", typeof import("../functions/routers/users").addToPlaylist>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/users").addToPlaylist>("routers/users:addToPlaylist"), { type: "mutation" }),
      deleteUserArticle: createApiLeaf<"mutation", typeof import("../functions/routers/users").deleteUserArticle>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/users").deleteUserArticle>("routers/users:deleteUserArticle"), { type: "mutation" }),
      getCurrentUser: createApiLeaf<"query", typeof import("../functions/routers/users").getCurrentUser>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/routers/users").getCurrentUser>("routers/users:getCurrentUser"), { type: "query" }),
      getUserPlaylist: createApiLeaf<"query", typeof import("../functions/routers/users").getUserPlaylist>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/routers/users").getUserPlaylist>("routers/users:getUserPlaylist"), { type: "query" }),
      saveUserProgress: createApiLeaf<"mutation", typeof import("../functions/routers/users").saveUserProgress>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/routers/users").saveUserProgress>("routers/users:saveUserProgress"), { type: "mutation" }),
    },
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

