// Regenerates src/lib/og-fonts.ts from the @expo-google-fonts packages.
//
// resvg rasterises the OG card's text itself, and the Worker it runs in has no
// filesystem to load fonts from -- so the faces are base64-embedded into a
// module the bundler can carry. Run this after changing which faces the card
// uses:
//
//   bun run scripts/embed-fonts.ts
//
// TTF, not woff: resvg's font database does not decode woff, and the failure is
// silent -- it renders the card with no text at all rather than erroring.
const FACES = [
  { const: 'INSTRUMENT_SANS_400', file: '@expo-google-fonts/instrument-sans/400Regular/InstrumentSans_400Regular.ttf' },
  { const: 'INSTRUMENT_SANS_700', file: '@expo-google-fonts/instrument-sans/700Bold/InstrumentSans_700Bold.ttf' },
  { const: 'NEWSREADER_700', file: '@expo-google-fonts/newsreader/700Bold/Newsreader_700Bold.ttf' },
];

let out = `// GENERATED by scripts/embed-fonts.ts -- do not edit by hand.
// Font faces for the OG card, base64-embedded because the Worker that renders
// it has no filesystem. See the script for why these are TTF and not woff.

function decode(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

`;

for (const face of FACES) {
  const path = Bun.resolveSync(face.file, import.meta.dir + '/..');
  const b64 = Buffer.from(await Bun.file(path).arrayBuffer()).toString('base64');
  out += `const ${face.const}_B64 =\n  '${b64}';\nexport const ${face.const} = /* @__PURE__ */ decode(${face.const}_B64);\n\n`;
}

await Bun.write(import.meta.dir + '/../src/lib/og-fonts.ts', out);
console.log('wrote src/lib/og-fonts.ts');
